/*
 * resultCodes.h
 *
 *  Created on: 24.10.2018
 *      Author: PKijanski
 */

#ifndef UTLIS_RESULTCODES_H_
#define UTLIS_RESULTCODES_H_

#include <stdint.h>

/**
 * @brief Local types
 */

typedef int32_t	result_t;

/**
 * @brief Generic error
 */

#define RESULT_SUCCESS					0x00000000
#define RESULT_ERROR					0x80000000

/**
 * @brief Subsystems definitions
 */
enum subSystemsDef
{
	LOGGER				= 0x1000,
	LED_DRIVER			= 0x2000,
	ULTRA_SOUND			= 0x3000,
	JOYSTICK_DRIVER		= 0x4000,
	LCD_NOKIA_5110		= 0x5000,
	TRANSMITTER_AM_433	= 0x6000,

	UTILS_COMP			= 0x99000,
};

enum resultCodesDefinition
{
	ERR_LOGGER_ERROR							= RESULT_ERROR | LOGGER,
	ERR_LOGGER_TASK_CRESTION_ERROR,
	ERR_LOGGER_NO_USART_PROVIDED,
	ERR_LOGGER_NEW_NODE_CREATION_ERROR,
	ERR_LOGGER_FIRST_NODE_NULL,
	ERR_LOGGER_QUEUE_FULL_ERROR,

	ERR_LED_DRIVER_ERROR						= RESULT_ERROR | LED_DRIVER,
	ERR_LED_DRIVER_TASK_CRESTION_ERROR,
	ERR_LED_DRIVER_NO_SPI_PROVIDED,
	ERR_LED_DRIVER_NO_DEVICES,
	ERR_LED_DRIVER_WRONG_DEVICE_SELECTED,

	ERR_ULTRA_SOUND_DRIVER_ERROR				= RESULT_ERROR | ULTRA_SOUND,
	ERR_ULTRA_SOUND_TASK_CRESTION_ERROR,
	ERR_ULTRA_SOUND_DRIVER_NOT_VALID_PARAMS,
	ERR_ULTRA_SOUND_TRIGGER_NOT_SET,
	ERR_ULTRA_SOUND_SEM_NOT_RELEASED,

	ERR_JOYSTICK_DRIVER_ERROR					= RESULT_ERROR | JOYSTICK_DRIVER,
	ERR_JOYSTICK_DRIVER_TASK_CRESTION_ERROR,
	ERR_JOYSTICK_DRIVER_NO_ADC_PROVIDED,

	ERR_LCD_NOKIA_5110_ERROR					= RESULT_ERROR | LCD_NOKIA_5110,
	ERR_LCD_NOKIA_5110_TASK_CREATION_ERROR,
	ERR_LCD_NOKIA_5110_NO_SPI_PROVIDED,
	ERR_LCD_NOKIA_5110_WRONG_INPUT_PARAMS,

	ERR_TRANSMITTER_AM_433_ERROR				= RESULT_ERROR | TRANSMITTER_AM_433,
	ERR_TRANSMITTER_AM_433_NOT_VALID_PARAMS,
	ERR_TRANSMITTER_AM_433_TASK_CRESTION_ERROR,

	ERR_UTILS_ERROR								= RESULT_ERROR | UTILS_COMP,
	ERR_UTILS_NULL_INPUT_BUF,
	ERR_UTILS_TO_BIG_NUMBER,
};

#endif /* UTLIS_RESULTCODES_H_ */
